name: CI
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pong Action
        uses: tree-1917/hurldm@main
        with:
          developer-name: "Main Developer"
